version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:10.1.0
    working_directory: ~/mailtrap-client
    steps:
      - checkout
      - run:
          name: "test"
          command: |
            npm install
            npm test
workflows:
  version: 2
  build-test-publish:
    jobs:
      - build-test
